language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t fescalhao/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true fescalhao/react-test npm test -- --coverage

after_success:
    - docker build -t fescalhao/multi-client ./client
    - docker build -t fescalhao/multi-nginx ./nginx
    - docker build -t fescalhao/multi-server ./server
    - docker build -t fescalhao/multi-worker ./worker
    # Log in to the docker CLI    
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push fescalhao/multi-client
    - docker push fescalhao/multi-nginx
    - docker push fescalhao/multi-server
    - docker push fescalhao/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-easit-1-3064326535249
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY